### ISSUE TITLE
Add Support for 1.6.4 Forge Gradle

### ISSUE THREAD

**Issue by jredfox** [anatawa12/ForgeGradle-1.2#219]
I fallowed all the instructions that worked for 1.7.10 but for some odd reason it doesn't work for forge gradle 1.6.4. I also tried downgrading java to java 7 with no luck. I tried appending "-1.6.4" under the minecraft section and it doesn't work with or without it.

[build.gradle.txt](https://github.com/anatawa12/ForgeGradle-1.2/files/15442503/build.gradle.txt)
[gradle-wrapper.properties.txt](https://github.com/anatawa12/ForgeGradle-1.2/files/15442504/gradle-wrapper.properties.txt)

**Comment by anatawa12** [comment]
I think 1.6.4 development is with sone other versions of ForgeGradle, isn't it?

Could you let me know original build.gradle and error message you got?

**Comment by jredfox** [comment]
original message
```
Unzipping C:\Users\jredfox\.gradle\wrapper\dists\gradle-4.4.1-bin\7pth8eae7h3dc5vcl4p1gpja4r\gradle-4.4.1-bin.zip to C:\Users\jredfox\.gradle\wrapper\dists\gradle-4.4.1-bin\7pth8eae7h3dc5vcl4p1gpja4r
Exception in thread "main" java.lang.RuntimeException: java.util.zip.ZipException: error in opening zip file
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)
        at org.gradle.wrapper.Install.createDist(Install.java:44)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:58)
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:231)
        at java.util.zip.ZipFile.<init>(ZipFile.java:156)
        at java.util.zip.ZipFile.<init>(ZipFile.java:170)
        at org.gradle.wrapper.Install.unzip(Install.java:157)
        at org.gradle.wrapper.Install.access$400(Install.java:26)
        at org.gradle.wrapper.Install$1.call(Install.java:67)
        at org.gradle.wrapper.Install$1.call(Install.java:44)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        ... 3 more
        ```

**Comment by jredfox** [comment]
[[PATCHED]forge-1.6.4-9.11.1.964-src.zip](https://github.com/anatawa12/ForgeGradle-1.2/files/15442753/PATCHED.forge-1.6.4-9.11.1.964-src.zip)
the patched forge 1.6.4 MDK I had archived says
```
FAILURE: Build failed with an exception.

* What went wrong:
The setupDecompWorkspace will only work with Java 7! This is fixed in ForgeGradle 1.2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.601 secs
```

**Comment by jredfox** [comment]
maybe you could make 1.7.10's forge gradle work with 1.6.4's. IDK the best solution all I know is none of the forge source's works anymore not the non forge gradle either

**Comment by Consumedgrub2** [comment]
Bump, you could try looking at this information: https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/modification-development/3134758-forgegradle-doesnt-work-cant-setup-1-6-4-workspace

**Comment by anatawa12** [comment]
No one answered my question yet.

> Could you let me know original build.gradle

I don't know where to get official mod development kit for 1.6.4 with ForgeGradle and which version of FG is used in it.

**Comment by Consumedgrub2** [comment]
Forge 1.6.4 uses forge gradle 1.0 maybe 1.1 I think? So not 1.2. It is possible to find the mdk here: https://files.minecraftforge.net/net/minecraftforge/forge/index_1.6.4.html and then selecting the src download option. In order to setup the workspace, you must follow along this tutorial I found here: https://www.planetminecraft.com/blog/164-crafticmcs-modding-tutorials-forge/, or I could just tell you in order to set it up, run the `install` file and it should be "good". But thats where the problem starts. Something about this version is weird because it's just before their modern toolchain, something I read on a forum post a couple months ago, but it gets setup errors due to broken links and the https issue. And it also requires Java 7 or 6, something like that which is harder to find, unless you just resort to the oracle jdk. I don't know exactly if forge gradle 1.0 can be bumped up to 1.2 to mod for 1.6.4 and potentially use this version, I'm unsure, most likely not, so I wouldn't know how to proceed until I found this modern fork for forge gradle 1.2. Whatever was done here would have to be done to https://github.com/MinecraftForge/ForgeGradle/tree/FG_1.0. (The 1.0 branch)

**Comment by anatawa12** [comment]
Thank you for answering.

> Forge 1.6.4 uses forge gradle 1.0 maybe 1.1 I think? So not 1.2.

OK. So we can expect to work with 1.2 since major version is not change but may not work.

> run the install file and it should be "good".

MDK for 1.7.10 or later won't need running script to get build.gradle so I was confused.
I'll try running install.sh

**Comment by anatawa12** [comment]
I tried to run `install.py` but failed with `Download of mcp8.11.zip failed hash check, deleting 1ecfa789fcf4d2ad5e6dcaeda336c55e 2d7a759309b5cc10ca29caa0b10f3bfc` (build 1345) so I need to find some version works or skip checksum checks

**Comment by jredfox** [comment]
> I tried to run `install.py` but failed with `Download of mcp8.11.zip failed hash check, deleting 1ecfa789fcf4d2ad5e6dcaeda336c55e 2d7a759309b5cc10ca29caa0b10f3bfc` (build 1345) so I need to find some version works or skip checksum checks

yes you have to use my branch in order to get non forge gradle MDK working for 1.6.4 and below. My suggestion was to try and get forge gradle to work on 1.6.4+ as it's not really working consistently across 1.6x - 1.7.2+ only certain versions like 1.7.10
https://github.com/jredfox/FoxyRetroMDK

**Comment by anatawa12** [comment]
So you mean we cannot get build.gradle from official for now?

**Comment by jredfox** [comment]
> So you mean we cannot get build.gradle from official for now?

yes this is correct for 1.6.4, 1.7.2 most 1.8 builds etc... Couldn't you just re-write and make a new gradle project that would download the right deps and then make forge do it's thing only when needed like building AT etc....? 

And if you choose to re-make it why not also make it work offline regardless if the `.xml` / `.pom` files it wants exists it should always assume if your not online that the old deps are the current deps. this is useful when you want to code offline in school or during a road / plane trip **IT ALSO ALLOWS MODDERS TO BUILD THEIR MOD EVEN WHEN GRADLE BREAKS (EVERY YEAR) - 2 YEARS**. In my opinion gradle isn't good but it's all we got for now

**Comment by anatawa12** [comment]
So what you want is support for 1.6.4 from scratch, and not porting to new Gradle or port from ForgeGradle 1.x, right?
if you don't have any (working or was working) MDK or project that with ForgeGradle (any version), this project would not add support for 1.6.4.
Please create another project to make userdev (the jar file provides required data for build) for FG 1.2, or possibly for FG3+ (which is compatible for FG4,5, and later)

**Comment by jredfox** [comment]
> So what you want is support for 1.6.4 from scratch, and not porting to new Gradle or port from ForgeGradle 1.x, right? if you don't have any (working or was working) MDK or project that with ForgeGradle (any version), this project would not add support for 1.6.4. Please create another project to make userdev (the jar file provides required data for build) for FG 1.2, or possibly for FG3+ (which is compatible for FG4,5, and later)

No I was asking wouldn't it make sense just to replace forge gradle at least all except the compile portions as a suggestion for all MC Versions 1.6 - 1.12.2

this still is a valid issue if you wish to continue trying to make broken forge gradle work for 1.6x

**Comment by anatawa12** [comment]
> No I was asking wouldn't it make sense just to replace forge gradle at least all except the compile portions as a suggestion for all MC Versions 1.6 - 1.12.2

Sorry. with my poor english, I cannot understand this statement correctly.
(Especially what "a suggestion for all MC Versions 1.6 - 1.12.2" means)

I think it would be good development experience if we can use ForgeGradle for almost all version of Forge.
However, it's not scope of this project (at least for now).
I don't have enough time working on this project to add and maintain support for new Forge versions.

> this still is a valid issue if you wish to continue trying to make broken forge gradle work for 1.6x

I want to ask for clarifying what "broken" mean. Is this "broken" mean originally not working or working before but not working for now?

-----

I clarify the purpose of this Project here: This project is to fix several problems of ForgeGradle with newer / modern Gradle, or newer / modern environments.
This project is NOT to extend ForgeGradle for Forge versions unsupported by ForgeGradle.

This may still be a valid issue if Forge 1.6.4 is (somewhat) supported by some version of ForgeGradle. (I want to know which version of FG and what configuration is used before)
However, if Forge 1.6.4 is never supported by any version of ForgeGradle, what this issue is asking is out of scope of this project.

**Comment by jredfox** [comment]
1.6.4-9.11.1.964

**Comment by anatawa12** [comment]
> > So you mean we cannot get build.gradle from official for now?
> 
> yes this is correct for 1.6.4, 1.7.2 most 1.8 builds etc...

You said no before.... but there is.

> 1.6.4-9.11.1.964

OK I downloaded [1.6.4-9.11.1.964](https://maven.minecraftforge.net/net/minecraftforge/forge/1.6.4-9.11.1.964/forge-1.6.4-9.11.1.964-src.zip) and I see it's gradle project.
I also see there is correct [userdev.jar](https://maven.minecraftforge.net/net/minecraftforge/forge/1.6.4-9.11.1.964/forge-1.6.4-9.11.1.964-userdev.jar) so I can start investigating if I can support this version of forge with this FG.

**Comment by Consumedgrub2** [comment]
Any updates? I came back to this myself.
